config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations", passwords: "admins/passwords" }

  namespace :admin do
    resources :ads, :users
    resources :places do
      get :autocomplete_place_name, :on => :collection
    end
    get 'welcome/index'
  end

  resources :marks, only: [:index, :create, :destroy]

  root 'admin/welcome#index'

  match 'auth',          to: 'auth#index',    via: [:get, :post]
  match 'profile',       to: 'profile#index', via: :get
  match 'users',         to: 'users#update',  via: :put
  match 'users',         to: 'users#create',  via: :post

  resources :users, only: [:nearby, :show] do
    get 'nearby', on: :collection 
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name,  presence: true, allow_blank: false
  validates :phone, presence: true, allow_blank: false

  has_many :ads

  scope :with_ads, ->(){ self.joins(:ads).having('COUNT(ads.id) > 0').group('places.id') }
  scope :within_radius, ->(object, radius = Settings.radius_of_places){ self.with_ads.near(object, radius).reorder("places.name DESC") }

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  autocomplete :place, :name, full: true, extra_data: [:phone, :address, :latitude, :longitude]

  # GET /admin/places
  def index
    @places = Place.all
  end

  # GET /admin/places/1
  def show
  end

  # GET /admin/places/new
  def new
    @place = Place.new
  end

  # GET /admin/places/1/edit
  def edit
  end

  # POST /admin/places
  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to [:admin, @place], notice: 'Place was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/places/1
  def update
    if @place.update(place_params)
      redirect_to [:admin, @place], notice: 'Place was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/places/1
  def destroy
    @place.destroy
    redirect_to admin_places_url, notice: 'Place was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def place_params
      params.require(:place).permit(:name, :phone, :address, :longitude, :latitude)
    end
end

app/views/admin/places/_form.html.erb
<%= form_for([:admin, @place]) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @place] %> |
<%= link_to 'Back', admin_places_path %>

app/views/admin/places/index.html.erb
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Lng</th>
      <th>Lat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |admin_place| %>
      <tr>
        <td><%= admin_place.name %></td>
        <td><%= admin_place.phone %></td>
        <td><%= admin_place.address %></td>
        <td><%= admin_place.longitude %></td>
        <td><%= admin_place.latitude %></td>
        <td><%= link_to 'Show', [:admin, admin_place] %></td>
        <td><%= link_to 'Edit', edit_admin_place_path(admin_place) %></td>
        <td><%= link_to 'Destroy', [:admin, admin_place], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_admin_place_path %>

app/views/admin/places/new.html.erb
<h1>New admin_place</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_places_path %>

app/views/admin/places/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pull-left">
  <p>
    <strong>Name:</strong>
    <%= @place.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @place.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @place.address %>
  </p>

  <p>
    <strong>Lng:</strong>
    <%= @place.longitude %>
  </p>

  <p>
    <strong>Lat:</strong>
    <%= @place.latitude %>
  </p>

  <% if @place.nearbys && !@place.nearbys.empty? %>
    <h3>Nearby Locations</h3>
    <ul>
      <% @place.nearbys.each do |place| %>
        <li><%= link_to place.address, [:admin, place] %> (<%= place.distance.round(2) %> kilometers)</li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="pull-right">

  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?&zoom=14&size=600x300&maptype=roadmap
  &markers=color:blue%7Clabel:S%7C#{@place.latitude},#{@place.longitude}" %>

</div>

<div class="clear">
  <%= link_to 'Edit', edit_admin_place_path(@place) %> |
  <%= link_to 'Back', admin_places_path %>
</div>