config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations", passwords: "admins/passwords" }

  namespace :admin do
    resources :ads, :users
    resources :places do
      get :autocomplete_place_name, :on => :collection
    end
    get 'welcome/index'
  end

  resources :marks, only: [:index, :create, :destroy]

  root 'admin/welcome#index'

  match 'auth',          to: 'auth#index',    via: [:get, :post]
  match 'profile',       to: 'profile#index', via: :get
  match 'users',         to: 'users#update',  via: :put
  match 'users',         to: 'users#create',  via: :post

  resources :users, only: [:nearby, :show] do
    get 'nearby', on: :collection 
  end

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  validates :name,     presence: true, allow_blank: false
  validates :place_id, presence: true, allow_blank: false

  belongs_to :place
  self.per_page = 10

  scope :random, ->(limit = 1){ self.order("RANDOM()").limit(limit) }
end

app/controllers/admin/ads_controller.rb
class Admin::AdsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_action :set_place, only: [:create]

  # GET /admin/ads
  def index
    @ads = Ad.all.paginate(page: params[:page])
  end

  # GET /admin/ads/1
  def show
  end

  # GET /admin/ads/new
  def new
    @ad = Ad.new
    @place = Place.new
  end

  # GET /admin/ads/1/edit
  def edit
  end

  # POST /admin/ads
  def create
    @ad = @place.ads.build(ad_params)
    if @ad.save
      redirect_to [:admin, @ad], notice: 'Ad was successfully created.'
    else
      render(action: :new)
    end
  end

  # PATCH/PUT /admin/ads/1
  def update
    if @ad.update(ad_params)
      redirect_to [:admin, @ad], notice: 'Ad was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/ads/1
  def destroy
    @ad.destroy
    redirect_to admin_ads_url, notice: 'Ad was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end
    def set_place
      if ad_params[:place_id] and not ad_params[:place_id].empty?
        @place = Place.find(ad_params[:place_id])
      else
        @place = Place.new(place_params)
        @ad = Ad.new(ad_params)
        render(action: :new) and return unless @place.save
      end
    end
    # Only allow a trusted parameter "white list" through.
    def ad_params
      params.require(:ad).permit(:name, :price, :photo, :place_id)
    end
    def place_params
      params.require(:place).permit(:name, :phone, :address, :latitude, :longitude)
    end 
end

app/views/admin/ads/_ad.html.erb
<div class="ad-wrapper">
  <%= render 'shared/item_controls', { edit_item_path: edit_admin_ad_path(ad), item: ad } %>
  <%= render 'shared/item_undercover', { undercover: ad.photo } %>
  <%= render 'shared/item_title', { item: ad, title: ad.name } %>
</div>

app/views/admin/ads/_form.html.erb
<%= simple_form_for([:admin, @ad], html: { class: 'form-horizontal' }) do |f| %>
  <%= render 'shared/error_messages', item: @ad %>
  <%= render 'shared/error_messages', item: @place %>

  <div class="form-inputs">
    <%= f.input :name, input_html: { class: 'form-control' }, placeholder: 'Капучіно' %>
  </div>
  <div class="form-inputs">
    <%= f.input :price, input_html: { class: 'form-control' }, placeholder: '18грн.' %>
  </div>
  <div class="form-inputs">
    <%= f.input :photo, input_html: { class: 'form-control', width: '400px' }, placeholder: 'http://example.com/image.png' %>
  </div>
  <div class="form-inputs">
    <%= f.input :place_id, as: :hidden %>
  </div>
  <%= simple_fields_for :place do |b| %>
    <div class="form-inputs">
      <%= b.input :name, as: :autocomplete, url: autocomplete_place_name_admin_places_path,
       id_element: '#ad_place_id', update_elements: { phone: '#place_phone', latitude: '#place_latitude', longitude: '#place_longitude' }, input_html: { class: 'form-control' }, label: 'Place (start typying for autocompletion)', placeholder: 'Японахата' %>
    </div>
    <div class="form-inputs">
      <%= b.input :phone, input_html: { class: 'extra_place_element form-control' }, placeholder: '0329876543' %>
    </div>
    <div class="form-inputs">
      <%= b.input :latitude, input_html: { class: 'extra_place_element form-control' } %>
    </div>
    <div class="form-inputs">
      <%= b.input :longitude, input_html: { class: 'extra_place_element form-control' } %>
    </div>
  <% end %>
  <br /><br />
  <div class="form-inputs">
    <%= f.button :submit, class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/admin/ads/edit.html.erb
<h1>Editing admin_ad</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @ad] %> |
<%= link_to 'Back', admin_ads_path %>

app/views/admin/ads/index.html.erb
<!-- show all ads-->
<% unless @ads.empty? %>
  <% @ads.each do |ad| %>
  <%= render partial: 'ad', locals: { ad: ad } %>
  <% end %>
<% else %>
  <!-- no ads found -->
<% end %>
<div class='clearfix'></div>

<%= render 'shared/pagination', items: @ads %>
<%= render 'shared/create_item', path: new_admin_ad_path %>

app/views/admin/ads/new.html.erb
<h1>New ad</h1>
<%= link_to 'Back', admin_ads_path, class: 'btn btn-default' %>
<%= render 'form' %>

app/views/admin/ads/show.html.erb
<p id="notice"><%= notice %></p>

<div class="">
  <%= image_tag(@ad.photo, size: '200x200', vspace: 10) %><br />
  <p>
    <strong>Name:</strong>
    <%= @ad.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @ad.price %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= @ad.place_id %>
  </p>
</div>


<%= link_to 'Edit', edit_admin_ad_path(@ad) %> |
<%= link_to 'Back', admin_ads_path %>